# coding=utf-8
TYPE_LOCAL = "local"
TYPE_PCC = "public_cloud"
TYPE_CC = "channel_center"
# local
LOCAL_HOST = '127.0.0.1'
LOCAL_PORT = 3306
LOCAL_USER = 'kevin'
LOCAL_PASSWD = '1234'
LOCAL_MINCASHED = 3
LOCAL_MAXCASHED = 100
LOCAL_MAXCONNECTIONS = 10